name: Rename

on:
  workflow_dispatch:
  push:
    branches: [ feat/oauth2-gateway ]

# Runs do not need to be concurrent
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  rename:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Replace instances
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

          git checkout feat/oauth2-gateway
          git checkout -b temp feat/oauth2-gateway
          rm -rf docs .github .readthedocs.yml tests
          mv discord discord_slayer_sdk

          sed -i -e 's/import discord/import discord_slayer_sdk/g' -e '/from discord_protos/!{s/from discord/from discord_slayer_sdk/g}' -e '/from discord_protos/!{s/from discord/from discord_slayer_sdk/g}' -e 's/discord\.py/discord_slayer_sdk\.py/g' -e '/\(discord\.com\|discord\.gift\|discord\.gg\|discord\.new\)/! s/discord\./discord_slayer_sdk\./g' $(find discord_slayer_sdk examples -name "*.py")
          sed -i -e 's/discord/discord_slayer_sdk/g' MANIFEST.in setup.py
          sed -i -E 's/^name = "discord\.py"/name = "discord_slayer_sdk.py"/; /http/!s/\bdiscord\b/discord_slayer_sdk/g' pyproject.toml

      - name: Push changes
        run: |
          git add .
          git stash
          git switch renamed
          git checkout stash -- .

          (git commit -am "Synchronize slaycord") || true
          (git push origin renamed) || true